package_rename_config:
  android:
    app_name: Writey
    package_name: com.blackbear.writey
   

  web:
    app_name: Writey
    description: A whiteboard app.

  windows:
    app_name: Writey
    organization: Black Bear
    copyright_notice: |
      Â© 2021 Black Bear
      All rights reserved.
    exe_name: Writey
